.TH "_registry_item" 3 "Thu Apr 16 2020" "Version 1.2" "Huffman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_registry_item
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "void * \fBp\fP"
.br
.ti -1c
.RI "size_t \fBsize\fP"
.br
.ti -1c
.RI "\fBcall_t\fP \fBcall\fP"
.br
.ti -1c
.RI "struct \fB_registry_item\fP * \fBnext\fP"
.br
.in -1c
.SH "Member data_ Documentation"
.PP 
.SS "\fBcall_t\fP _registry_item::call"

.SS "struct \fB_registry_item\fP* _registry_item::next"

.SS "void* _registry_item::p"

.SS "size_t _registry_item::size"


.SH "Author"
.PP 
Generated automatically by Doxygen for Huffman from the source code\&.
