.TH "call_t" 3 "Thu Apr 16 2020" "Version 1.2" "Huffman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
call_t
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBf\fP"
.br
.ti -1c
.RI "int \fBline\fP"
.br
.ti -1c
.RI "char * \fBpar_txt\fP"
.br
.ti -1c
.RI "char * \fBfile\fP"
.br
.in -1c
.SH "Member data_ Documentation"
.PP 
.SS "int call_t::f"

.SS "char* call_t::file"

.SS "int call_t::line"

.SS "char* call_t::par_txt"


.SH "Author"
.PP 
Generated automatically by Doxygen for Huffman from the source code\&.
