.TH "End" 3 "Thu Apr 16 2020" "Version 1.2" "Huffman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
End
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <node\&.h>\fP
.PP
Inherits \fBNode\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEnd\fP (\fBLetter\fP &\fBletter\fP, long frequency)"
.br
.ti -1c
.RI "\fBEnd\fP (const \fBEnd\fP &end)"
.br
.ti -1c
.RI "\fBEnd\fP ()"
.br
.ti -1c
.RI "\fBLetter\fP & \fBletter\fP ()"
.br
.ti -1c
.RI "\fBNode\fP * \fBLeft\fP () const"
.br
.ti -1c
.RI "\fBNode\fP * \fBRight\fP () const"
.br
.ti -1c
.RI "bool \fBoperator==\fP (\fBEnd\fP &e)"
.br
.ti -1c
.RI "void \fBoperator++\fP (int)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "End::End (\fBLetter\fP & letter, long frequency)\fC [inline]\fP"

.SS "End::End (const \fBEnd\fP & end)\fC [inline]\fP"

.SS "End::End ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBNode\fP* End::left () const\fC [inline]\fP"

.SS "\fBLetter\fP& End::letter ()\fC [inline]\fP"

.SS "void End::operator++ (int)\fC [inline]\fP"

.SS "bool End::operator== (\fBEnd\fP & e)\fC [inline]\fP"

.SS "\fBNode\fP* End::right () const\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Huffman from the source code\&.
