.TH "huffman.cpp" 3 "Thu Apr 16 2020" "Version 1.2" "Huffman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
huffman.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'memtrace\&.h'\fP
.br
\fC#include 'huffman\&.h'\fP
.br
\fC#include 'node\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Huffman from the source code\&.
