.TH "main.cpp" 3 "Thu Apr 16 2020" "Version 1.2" "Huffman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
main.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include 'gtest_lite\&.h'\fP
.br
\fC#include 'memtrace\&.h'\fP
.br
\fC#include 'bitbuffer\&.h'\fP
.br
\fC#include 'letter\&.h'\fP
.br
\fC#include 'huffman\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMEMTRACE\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define MEMTRACE"

.SH "Function Documentation"
.PP 
.SS "int main ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for Huffman from the source code\&.
