.TH "node.h" 3 "Thu Apr 16 2020" "Version 1.2" "Huffman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
node.h
.SH SYNOPSIS
.br
.PP
\fC#include 'letter\&.h'\fP
.br
\fC#include <cstdlib>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBNode\fP"
.br
.ti -1c
.RI "class \fBEnd\fP"
.br
.ti -1c
.RI "class \fBPath\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Huffman from the source code\&.
