.TH "Path" 3 "Thu Apr 16 2020" "Version 1.2" "Huffman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Path
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <node\&.h>\fP
.PP
Inherits \fBNode\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPath\fP (\fBNode\fP *l, \fBNode\fP *r)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Path::Path (\fBNode\fP * l, \fBNode\fP * r)\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Huffman from the source code\&.
